.deploy_template: &deploy_job_definition
  image: openshift/origin-cli:v3.10
  stage: deploy
  before_script:
    - oc version
    - oc login https://${DEPLOY_ADDRESS} --token=${DEPLOY_TOKEN}
    - oc project ${DEPLOY_PROJECT}
    -  - oc process -f .okd/DeploymentConfig.yaml --param APP_IMAGE=${CONTAINER_REGISTRY_IMAGE} --param SERVICE_NAME=${DEPLOY_SERVICE_NAME} | oc apply -f -
    - |
      oc process -f .okd/ConfigMap.yaml \
        --param SERVICE_NAME="${DEPLOY_SERVICE_NAME}" \
        --param APP_VERSION="${PROJECT_VERSION}" \
        --param REDIS_ADDR="${DEPLOY_REDIS_ADDR}" \
        --param REDIS_PASS="${DEPLOY_REDIS_PASS}" \
        --param TRACER_ENABLED=${DEPLOY_TRACER_ENABLED} \
        --param TRACER_HOST=${DEPLOY_TRACER_HOST} \
        --param CI_COMMIT_REF_SLUG="${CI_COMMIT_REF_SLUG}" | oc apply -f -
    - |
      oc process -f .okd/Secret.yaml \
        --param SERVICE_NAME="${DEPLOY_SERVICE_NAME}" \
        --param APP_VERSION="${PROJECT_VERSION}" \
        --param CI_COMMIT_REF_SLUG="${CI_COMMIT_REF_SLUG}" \
        --param PASSENGER_HASH_SALT="${DEPLOY_PASSENGER_SALT}" \
        --param PASSENGER_HASH_LENGTH=15 \
        --param DRIVER_HASH_SALT="${DEPLOY_DRIVER_SALT}" \
        --param DRIVER_HASH_LENGTH=15 \
        --param DRIVER_JWT_PUBLIC_KEY="${DEPLOY_DRIVER_JWT_PUBLIC_KEY}" \
        --param PASSENGER_JWT_PUBLIC_KEY="${DEPLOY_PASSENGER_JWT_PUBLIC_KEY}" \
        --param THIRD_PARTY_JWT_PUBLIC_KEY="${DEPLOY_THIRD_PARTY_JWT_PUBLIC_KEY}" \
        --param THIRD_PARTY_JWT_PRIVATE_KEY="${DEPLOY_THIRD_PARTY_JWT_PRIVATE_KEY}" | oc apply -f -
    - |
      oc process -f .okd/AutoScaler.yaml \
        --param MIN_REPLICA=${DEPLOY_MIN_REPLICA} \
        --param MAX_REPLICA=${DEPLOY_MAX_REPLICA} \
        --param CPU_UTILIZATION=${DEPLOY_CPU_UTILIZATION} | oc apply -f -
    - oc process -f .okd/Route.yaml --param APP_HOST=${DEPLOY_SERVICE_NAME} --param SERVICE_NAME=${DEPLOY_SERVICE_NAME} | oc apply -f -
    - oc process -f .okd/Service.yaml --param SERVICE_NAME=${DEPLOY_SERVICE_NAME} | oc apply -f -
  script:
    - oc rollout latest dc/${DEPLOY_SERVICE_NAME}
  only:
    - tags
  except:
    variables:
      - $UPDATE_ENVIRONMENT_VARIABLE
  when: manual

deploy:staging:teh_1:
  <<: *deploy_job_definition
  variables:
    DEPLOY_MIN_REPLICA: "1"
    DEPLOY_MAX_REPLICA: "2"
    DEPLOY_CPU_UTILIZATION: "80"
    CONTAINER_REGISTRY_IMAGE: "$PROJECT_STAGING/${PROJECT_SERVICE_NAME}:$CI_COMMIT_REF_SLUG"
    DEPLOY_ADDRESS: "${OKD_TEH1_CLUSTER_ADDRESS}"
    DEPLOY_PROJECT: "${PROJECT_STAGING}"
    DEPLOY_TOKEN: "${OKD_STAGING_TOKEN}"
    DEPLOY_PASSENGER_SALT: "${PASSENGER_SALT_DEV}"
    DEPLOY_DRIVER_SALT: "${DRIVER_SALT_DEV}"
    DEPLOY_SERVICE_NAME: "${PROJECT_SERVICE_NAME}-staging"
    DEPLOY_DRIVER_JWT_PUBLIC_KEY: "${DRIVER_JWT_PUBLIC_KEY_MOZART}"
    DEPLOY_PASSENGER_JWT_PUBLIC_KEY: "${PASSENGER_JWT_PUBLIC_KEY_MOZART}"
    DEPLOY_THIRD_PARTY_JWT_PUBLIC_KEY: "${THIRD_PARTY_JWT_PUBLIC_KEY_MOZART}"
    DEPLOY_THIRD_PARTY_JWT_PRIVATE_KEY: "${THIRD_PARTY_JWT_PRIVATE_KEY_MOZART}"
    DEPLOY_REDIS_ADDR: "soteria-redis-haproxy:6379"
    DEPLOY_TRACER_ENABLED: "false"
    DEPLOY_TRACER_HOST: "localhost"

  only:
    - master
    - branches
  except:
    variables:
      - $UPDATE_ENVIRONMENT_VARIABLE
  needs: ["release:staging"]

deploy:production:teh_1:
  <<: *deploy_job_definition
# Extends the global template so it add an after_script step for deployment announcement
  extends: .deployments_after_script
  variables:
    DEPLOY_MIN_REPLICA: "3"
    DEPLOY_MAX_REPLICA: "20"
    DEPLOY_CPU_UTILIZATION: "65"
    CONTAINER_REGISTRY_IMAGE: "$PROJECT_PRODUCTION_TEH1/$PROJECT_SERVICE_NAME:$CI_COMMIT_REF_SLUG"
    DEPLOY_ADDRESS: "${OKD_TEH1_CLUSTER_ADDRESS}"
    DEPLOY_PROJECT: "${PROJECT_PRODUCTION_TEH1}"
    DEPLOY_TOKEN: "${OKD_PRODUCTION_TOKEN_TEH1}"
    DEPLOY_PASSENGER_SALT: "${PASSENGER_SALT_PRODUCTION}"
    DEPLOY_DRIVER_SALT: "${DRIVER_SALT_PRODUCTION}"
    DEPLOY_SERVICE_NAME: "${PROJECT_SERVICE_NAME}"
    DEPLOY_DRIVER_JWT_PUBLIC_KEY: "${DRIVER_JWT_PUBLIC_KEY_PRODUCTION}"
    DEPLOY_PASSENGER_JWT_PUBLIC_KEY: "${PASSENGER_JWT_PUBLIC_KEY_PRODUCTION}"
    DEPLOY_THIRD_PARTY_JWT_PUBLIC_KEY: "${THIRD_PARTY_JWT_PUBLIC_KEY_PRODUCTION}"
    DEPLOY_THIRD_PARTY_JWT_PRIVATE_KEY: "${THIRD_PARTY_JWT_PRIVATE_KEY_PRODUCTION}"
    DEPLOY_REDIS_ADDR: "soteria-redis-haproxy.realtime-production.svc:6379"
    CI_DEPLOYMENT_INFRA: "teh-1"
    DEPLOY_TRACER_ENABLED: "false"
    DEPLOY_TRACER_HOST: "localhost"
  needs: ["release:production:teh-1"]

deploy:production:teh_2:
  <<: *deploy_job_definition
# Extends the global template so it add an after_script step for deployment announcement
  extends: .deployments_after_script
  variables:
    DEPLOY_MIN_REPLICA: "3"
    DEPLOY_MAX_REPLICA: "20"
    DEPLOY_CPU_UTILIZATION: "70"
    CONTAINER_REGISTRY_IMAGE: "$PROJECT_PRODUCTION_TEH2/$PROJECT_SERVICE_NAME:$CI_COMMIT_REF_SLUG"
    DEPLOY_ADDRESS: "${OKD_TEH2_CLUSTER_ADDRESS}"
    DEPLOY_PROJECT: "${PROJECT_PRODUCTION_TEH2}"
    DEPLOY_TOKEN: "${OKD_PRODUCTION_TOKEN_TEH2}"
    DEPLOY_PASSENGER_SALT: "${PASSENGER_SALT_PRODUCTION}"
    DEPLOY_DRIVER_SALT: "${DRIVER_SALT_PRODUCTION}"
    DEPLOY_SERVICE_NAME: "${PROJECT_SERVICE_NAME}"
    DEPLOY_DRIVER_JWT_PUBLIC_KEY: "${DRIVER_JWT_PUBLIC_KEY_PRODUCTION}"
    DEPLOY_PASSENGER_JWT_PUBLIC_KEY: "${PASSENGER_JWT_PUBLIC_KEY_PRODUCTION}"
    DEPLOY_THIRD_PARTY_JWT_PUBLIC_KEY: "${THIRD_PARTY_JWT_PUBLIC_KEY_PRODUCTION}"
    DEPLOY_THIRD_PARTY_JWT_PRIVATE_KEY: "${THIRD_PARTY_JWT_PRIVATE_KEY_PRODUCTION}"
    DEPLOY_REDIS_ADDR: "soteria-redis-haproxy.realtime-production.svc:6379"
    CI_DEPLOYMENT_INFRA: "teh-2"
    DEPLOY_TRACER_ENABLED: "false"
    DEPLOY_TRACER_HOST: "localhost"
  needs: ["release:production:teh-2"]
