---
release:staging:teh-1:
  extends: .easy_ci:release:docker
  variables:
    OKD4_TEH1_REGISTRY: "image-registry.apps.private.okd4.teh-1.snappcloud.io"
    RELEASE_CONTAINER_REGISTRY_ADDRESS: "$OKD4_TEH1_REGISTRY"
    RELEASE_CONTAINER_REGISTRY_IMAGE: "$OKD4_TEH1_REGISTRY/realtime-staging/$CI_PROJECT_NAME"
    RELEASE_CONTAINER_REGISTRY_USERNAME: "gitlab-ci"
    RELEASE_CONTAINER_REGISTRY_PASSWORD: ${OKD4_TEH1_REALTIME_STAGING_TOKEN}
  dependencies:
    - build
  only:
    - tags
    - branches
  when: manual

release:staging:teh-2:
  extends: .easy_ci:release:docker
  variables:
    OKD4_TEH2_REGISTRY: "image-registry.apps.private.okd4.teh-2.snappcloud.io"
    RELEASE_CONTAINER_REGISTRY_ADDRESS: "$OKD4_TEH2_REGISTRY"
    RELEASE_CONTAINER_REGISTRY_IMAGE: "$OKD4_TEH2_REGISTRY/realtime-staging/$CI_PROJECT_NAME"
    RELEASE_CONTAINER_REGISTRY_USERNAME: "gitlab-ci"
    RELEASE_CONTAINER_REGISTRY_PASSWORD: ${OKD4_TEH2_REALTIME_STAGING_TOKEN}
  dependencies:
    - build
  only:
    - tags
    - branches
  when: manual

release:mozart:
  extends: .easy_ci:release:docker
  variables:
    OKD4_TEH1_REGISTRY: "image-registry.apps.private.okd4.teh-1.snappcloud.io"
    RELEASE_CONTAINER_REGISTRY_IMAGE: "$OKD4_TEH1_REGISTRY/mozart/$CI_PROJECT_NAME"
    RELEASE_CONTAINER_REGISTRY_USERNAME: "gitlab-ci"
    RELEASE_CONTAINER_REGISTRY_PASSWORD: "$OKD_MOZART_TOKEN"
  dependencies:
    - build
  only:
    - tags
    - branches
  when: manual

release:production:teh-1:
  extends: .easy_ci:release:docker
  variables:
    OKD4_TEH1_REGISTRY: "image-registry.apps.private.okd4.teh-1.snappcloud.io"
    RELEASE_CONTAINER_REGISTRY_ADDRESS: "$OKD4_TEH1_REGISTRY"
    RELEASE_CONTAINER_REGISTRY_IMAGE: "$OKD4_TEH1_REGISTRY/realtime-production/$CI_PROJECT_NAME"
    RELEASE_CONTAINER_REGISTRY_USERNAME: "gitlab-ci"
    RELEASE_CONTAINER_REGISTRY_PASSWORD: ${OKD4_TEH1_REALTIME_PRODUCTION_TOKEN}
  dependencies:
    - build
  only:
    - tags
  when: manual

release:production:teh-2:
  extends: .easy_ci:release:docker
  variables:
    OKD4_TEH2_REGISTRY: "image-registry.apps.private.okd4.teh-2.snappcloud.io"
    RELEASE_CONTAINER_REGISTRY_ADDRESS: "$OKD4_TEH2_REGISTRY"
    RELEASE_CONTAINER_REGISTRY_IMAGE: "$OKD4_TEH2_REGISTRY/realtime-production/$CI_PROJECT_NAME"
    RELEASE_CONTAINER_REGISTRY_USERNAME: "gitlab-ci"
    RELEASE_CONTAINER_REGISTRY_PASSWORD: ${OKD4_TEH2_REALTIME_PRODUCTION_TOKEN}
  dependencies:
    - build
  only:
    - tags
  when: manual

release:production:baly:
  extends: .easy_ci:release:docker
  variables:
    BALY_REGISTRY: "registry.apps.internal.okd.eu-central-1.cloud.baly.app"
    RELEASE_CONTAINER_REGISTRY_ADDRESS: "$BALY_REGISTRY"
    RELEASE_CONTAINER_REGISTRY_IMAGE: "$BALY_REGISTRY/baly-dispatching/$CI_PROJECT_NAME"
    RELEASE_CONTAINER_REGISTRY_USERNAME: "gitlab-ci"
    RELEASE_CONTAINER_REGISTRY_PASSWORD: ${BALY_DISPATCHING_PRODUCTION_TOKEN}
  dependencies:
    - build
  only:
    - tags
  when: manual
