---
lint:
  extends: .easy_ci:lint

handolint:
  extends: .easy-ci:dockerfile:lint

test:
  image: registry.snapp.tech/docker/golang:1.19-alpine
  stage: test
  coverage: '/total:\s*\(statements\)\s*([\d.]+)%/'
  extends: .easy_ci:go:cache
  script:
    - go test -gcflags=-l -v -coverprofile .coverage.out ./...
    - go tool cover -func .coverage.out
  dependencies:
    - compile
