---
.go_mod_config: &go_mod
  image: registry.snapp.tech/docker/golang:1.17-alpine3.14
  cache:
    policy: pull
    paths:
      - vendor/
  before_script:
    - go env -w GOPROXY="https://repo.snapp.tech/repository/goproxy/"

unit_tests:
  <<: *go_mod
  stage: test
  coverage: '/total:\s*\(statements\)\s*([\d.]+)%/'
  script:
    - go test -gcflags=-l -v -coverprofile .coverage.out.tmp ./...
    - cat .coverage.out.tmp | grep -v "mock.go" > .coverage.out
    - rm -rf .coverage.out.tmp
    - go tool cover -func .coverage.out
  dependencies:
    - compile
