---
lint:
  extends: .easy_ci:lint

handolint:
  extends: .easy-ci:dockerfile:lint

test:
  image: registry.snapp.tech/docker/golang:1.18-alpine
  stage: test
  coverage: '/total:\s*\(statements\)\s*([\d.]+)%/'
  before_script:
    - go env -w GOPROXY="https://repo.snapp.tech/repository/goproxy/"
  script:
    - go test -gcflags=-l -v -coverprofile .coverage.out ./...
    - go tool cover -func .coverage.out
  dependencies:
    - compile
