apiVersion: v1
kind: Template
metadata:
  name: ${SERVICE_NAME}
objects:
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${SERVICE_NAME}
      app.snappcloud.io/name: ${SERVICE_NAME}
      app.snappcloud.io/instance: ${SERVICE_NAME}-${CI_COMMIT_REF_SLUG}
      app.snappcloud.io/version: ${CI_COMMIT_REF_SLUG}
      app.snappcloud.io/managed-by: bravo
      app.snappcloud.io/created-by: ${CREATED_BY}
    name: ${SERVICE_NAME}-tcp
  spec:
    host: ${SERVICE_NAME}-${SERVICE_NAMESPACE}.apps.private.teh-1.snappcloud.io
    port:
      targetPort: ${SERVICE_NAME}-tcp
    to:
      kind: Service
      name: ${SERVICE_NAME}
      weight: 100
    wildcardPolicy: None

parameters:
- name: SERVICE_NAME
  displayName: Service name
  description: The name of the application (should be unique in the namespace)
  required: true
  value: soteria
- name: SERVICE_NAMESPACE
  displayName: Application Unique ID
  required: true
  value: "snapp-ode-mozart"
- name: CREATED_BY
  displayName: Service name
  required: true
  value: mozart
- name: CI_COMMIT_REF_SLUG
  displayName: Commit Ref Slug
  required: true
  value: "qe"
