apiVersion: v1
kind: Template
metadata:
  name: ${SERVICE_NAME}-secret-tpl
objects:
  - apiVersion: v1
    kind: Secret
    type: Opaque
    metadata:
      name: "${SERVICE_NAME}-auth-env"
      labels:
        app.snappcloud.io/name: ${SERVICE_NAME}
        app.snappcloud.io/instance: ${SERVICE_NAME}-${CI_COMMIT_REF_SLUG}
        app.snappcloud.io/version: ${CI_COMMIT_REF_SLUG}
        app.snappcloud.io/managed-by: bravo
        app.snappcloud.io/created-by: ${CREATED_BY}
        app: ${SERVICE_NAME}
    stringData:
      CHANNEL_PREFIX: "emqch-"
      JWT_BASE_PATH: "/jwt_pems/"
      SALT_1: "${PASSENGER_HASH_SALT}"
      HASH_LENGTH_1: "${PASSENGER_HASH_MIN_LENGTH}"
      SALT_0: "${DRIVER_HASH_SALT}"
      HASH_LENGTH_0: "${DRIVER_HASH_MIN_LENGTH}"
      ISS_TYPE_0: "driver"
      ISS_TYPE_1: "passenger"
      ISS_TYPE_100: "third party"
      THIRDPARTY_CONFIG: "${VENDOR_APPLICATION_DATA}"

parameters:
  - name: PASSENGER_HASH_SALT
    displayName: Passenger hash salt for HashIds
    value: "secret"
    required: true
  - name: PASSENGER_HASH_MIN_LENGTH
    displayName: Minimum length of passenger generated hash for HashIds
    value: "15"
  - name: DRIVER_HASH_SALT
    displayName: Passenger hash salt for HashIds
    value: "secret"
    required: true
  - name: DRIVER_HASH_MIN_LENGTH
    displayName: Minimum length of driver generated hash for HashIds
    value: "15"
  - name: VENDOR_APPLICATION_DATA
    displayName: Vendor Application Data
    description: The configuration of 3rd parties application
    required: true
    value: "ewogICAiYm94Ijp7CiAgICAgICJ0eXBlIjoic3Vic2NyaWJlciIsCiAgICAgICJ0b2tlbiI6IktKSWlraklLYklZVkdqKVlpaFlVR0lCJiIsCiAgICAgICJ0b3BpY3MiOiJidWNrcywgMTExMSIsCiAgICAgICJleHAiOjg2NDAwCiAgIH0sCiAgICJoZXJhbGQtcHVibGlzaCI6ewogICAgICAidHlwZSI6InB1Ymxpc2giLAogICAgICAidG9rZW4iOiJ1dTBKVlB0aygxbnRHYWN1IiwKICAgICAgInRvcGljcyI6IioiLAogICAgICAiZXhwIjoxNTc2ODAwMDAKICAgfSwKICAgImhlcmFsZC1zdWJzY3JpYmVyIjp7CiAgICAgICJ0eXBlIjoic3Vic2NyaWJlciIsCiAgICAgICJ0b2tlbiI6InV1MEpWUHRrKDFudEdhY3UiLAogICAgICAidG9waWNzIjoiKiIsCiAgICAgICJleHAiOjE1NzY4MDAwMAogICB9LAogICAiY29sb255LXN1YnNjcmliZXIiOnsKICAgICAgInR5cGUiOiJzdWJzY3JpYmVyIiwKICAgICAgInRva2VuIjoidXUwSlZQdGsoMW50R2FjdXpwIiwKICAgICAgInRvcGljcyI6IioiLAogICAgICAiZXhwIjoxNTc2ODAwMDAKICAgfQp9"
  - name: SERVICE_NAME
    displayName: Service name
    description: The name of the application (should be unique in the namespace)
    value: "soteria"
  - name: CREATED_BY
    displayName: Created By
    required: true
    value: mozart
  - name: CI_COMMIT_REF_SLUG
    displayName: Commit Ref Slug
    required: true
    value: "qe"
