apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${SERVICE_NAME}
      labels:
        app.snappcloud.io/name: ${SERVICE_NAME}
        app.snappcloud.io/instance: ${SERVICE_NAME}-${CI_COMMIT_REF_SLUG}
        app.snappcloud.io/version: ${CI_COMMIT_REF_SLUG}
        app.snappcloud.io/managed-by: bravo
        app.snappcloud.io/created-by: ${CREATED_BY}
        app: "${SERVICE_NAME}"
    spec:
      ports:
      - name: ${SERVICE_NAME}-tcp
        port: 9999
        protocol: TCP
        targetPort: 9999
      selector:
        deploymentconfig: ${SERVICE_NAME}
parameters:
  - name: SERVICE_NAME
    displayName: Service name
    required: true
    value: "soteria"
  - name: CREATED_BY
    displayName: Created By
    required: true
    value: mozart
  - name: CI_COMMIT_REF_SLUG
    displayName: Commit Ref Slug
    required: true
    value: "qe"