apiVersion: v1
kind: Template
metadata:
  name: ${SERVICE_NAME}-configmap-tpl
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${SERVICE_NAME}-jwt-keys
    labels:
      app: ${SERVICE_NAME}
  data:
    100.private.pem: ${THIRD_PARTY_JWT_PRIVATE_KEY}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${SERVICE_NAME}-env
    labels:
      app: ${SERVICE_NAME}
  data:
    SOTERIA_PORT: "9999"
    SOTERIA_REDIS_ADDRESS: "${REDIS_ADDR}"
    SOTERIA_REDIS_POOL_SIZE: "10"
    SOTERIA_REDIS_MAX_RETRIES: "0"
    SOTERIA_REDIS_READ_TIMEOUT: "3s"
    SOTERIA_REDIS_POOL_TIMEOUT: "4s"
    SOTERIA_REDIS_MIN_RETRY_BACKOFF: "8ms"
    SOTERIA_REDIS_MAX_RETRY_BACKOFF: "512ms"
    SOTERIA_REDIS_IDLE_TIMEOUT: "300s"
    SOTERIA_REDIS_IDLE_CHECK_FREQUENCY: "60s"
    SOTERIA_REDIS_SET_MEMBER_EXP_TIME: "300s"
    SOTERIA_LOGGER_LEVEL: "${LOG_LEVEL}"
    SOTERIA_LOGGER_SENTRY_ENABLED: "false"
    SOTERIA_LOGGER_SENTRY_DSN: ""
    SOTERIA_LOGGER_SENTRY_TIMEOUT: "500ms"
    SOTERIA_JWK_KEY_PATH: ${JWT_KEY_PATH}
    
parameters:
- name: SERVICE_NAME
  displayName: Service name
  description: The name of the application (should be unique in the namespace)
- name: LOG_LEVEL
  value: "INFO"
  displayName: Log Level
  description: How much log do you want? (DEBUG|INFO|WARN|ERROR|OFF)
- name: JWT_KEY_PATH
  displayName: Private Key Path
  description: Private key Path
  value: "/jwt_pems/""
  required: true
- name: REDIS_ADDR
  required: true
  value: "rediscentral:6379"
- name: THIRD_PARTY_JWT_PRIVATE_KEY
  displayName: Third party Private Key
  description: Private key of third party's token
  required: true

