apiVersion: v1
kind: Template
metadata:
  name: ${SERVICE_NAME}-svc-tpl
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    ports:
    - name: 9999-tcp
      port: 9999
      protocol: TCP
      targetPort: 9999
    - name: 50051-tcp
      port: 50051
      protocol: TCP
      targetPort: 50051
    selector:
      app: ${SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
parameters:
- name: SERVICE_NAME
  displayName: Service name
  description: The name of the application (should be unique in the namespace)
  value: "soteria"
- name: PORT
  displayName: Port
  description: the port which will be open by your application
