---
linters:
  enable-all: true
  disable:
    # we don't use json with camel-case
    - tagliatelle
    # it should improve to support more known patterns
    - varnamelen
    - ireturn
    - musttag
    - depguard
    # deprecated linters
    - maligned
    - scopelint
    - golint
    - interfacer
    - exhaustivestruct
    - nolintlint
