---
run:
  tests: false
linters:
  enable-all: true
  disable:
    # we don't use json with camel-case
    - tagliatelle
    # it should improve to support more known patterns
    - varnamelen
    # deprecated linters
    - maligned
    - scopelint
    - golint
    - interfacer
linters-settings:
  gosec:
    excludes:
      # crypto/md5
      - G501
