version: '3.7'
services:
  soteria:
    container_name: soteria
    image: soteria:latest
    working_dir: /go/src/app
    ports:
      - 9999:9999
      - 50051:50051
    volumes:
      - .:/go/src/app
    depends_on:
      - redis
    environment:
      SOTERIA_LOGGER_LEVEL: 'DEBUG'
      SOTERIA_JWT_KEYS_PATH: '/go/src/app/test/'
      SOTERIA_HTTP_PORT: '9999'
      SOTERIA_GRPC_PORT: '50051'
      SOTERIA_REDIS_ADDRESS: 'redis:6379'
  redis:
    image: redis
    container_name: soteria-redis
    ports:
      - 6379:6379
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      - "6831:6831/udp"
      - 14250:14250
