version: '3.7'
services:
  soteria:
    container_name: soteria
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: go run cmd/soteria/soteria.go serve
    working_dir: /go/src/app
    ports:
      - 9999:9999
      - 50051:50051
    volumes:
      - .:/go/src/app
    depends_on:
      - redis
    environment:
      SOTERIA_HTTP_PORT: '9999'
      SOTERIA_GRPC_PORT: '50051'
      SOTERIA_REDIS_ADDRESS: 'redis:6379'
  redis:
    image: redis
    container_name: soteria-redis
    ports:
      - 6379:6379