# Default values for Soteria.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


image:
  registry: docker-registry.default.svc:5000
  repository: realtime-staging/soteria
  tag: dev
  pullPolicy: Always

resources:
  limits:
    memory: 128Mi
    cpu: 2
  requests:
    memory: 128Mi
    cpu: 1

envs:
  http_port: "9999"
  grpc_port: "50051"
  mode: "debug"
  redis_address: "main-redis-master.dispatching-staging.svc:6379"
  redis_pass: ""
  redis_pool_size: "10"
  redis_max_retries: "0"
  redis_read_timeout: "3s"
  redis_pool_timeout: "4s"
  redis_min_retry_backoff: "8ms"
  redis_max_retry_backoff: "512ms"
  redis_idle_timeout: "300s"
  redis_idle_check_frequency: "60s"
  redis_set_member_exp_time: "300s"
  redis_min_idle_connections: "5"
  logger_level: "debug"
  logger_sentry_enabled: "false"
  logger_sentry_dsn: ""
  logger_sentry_timeout: "500ms"
  allowed_access_types: "sub,pub"
  cache_enabled: "true"
  cache_expiration: "600s"

db:
  - meta_data:
      model_name: user
      date_created: '2020-09-29T10:44:15.106544359+03:30'
      date_modified: '2020-09-29T10:44:15.106544423+03:30'
    username: driver
    password: password
    type: EMQUser
    ips:
    secret: secret
    token_expiration_duration: 2592000000000000
    rules:
    - uuid: 84df6017-a850-42a3-a06f-22306a006a8d
      endpoint: ''
      topic: cab_event
      access_type: '1'
    - uuid: df0b884e-41dc-444e-81d4-67f62ae2174c
      endpoint: ''
      topic: driver_location
      access_type: '2'
    - uuid: 1375192a-6fc5-4409-abd8-0d21ef106bee
      endpoint: ''
      topic: shared_location
      access_type: '1'
    - uuid: d7aeb294-6271-470a-987a-01ea4f035e5d
      endpoint: ''
      topic: superapp_event
      access_type: '1'
  - meta_data:
      model_name: user
      date_created: '2020-09-29T10:44:15.106560757+03:30'
      date_modified: '2020-09-29T10:44:15.106560814+03:30'
    username: passenger
    password: password
    type: EMQUser
    ips:
    secret: secret
    token_expiration_duration: 2592000000000000
    rules:
    - uuid: a51f1898-3381-456f-a5fe-0e9d80b5bee0
      endpoint: ''
      topic: cab_event
      access_type: '1'
    - uuid: 8de97e3f-e772-4da4-8f15-4dc048f5c06e
      endpoint: ''
      topic: superapp_event
      access_type: '1'
    - uuid: c41260ed-70eb-4554-bc15-5714fc1bf3f8
      endpoint: ''
      topic: passenger_location
      access_type: '2'
    - uuid: 1375192a-6fc5-4409-abd8-0d21ef106bee
      endpoint: ''
      topic: shared_location
      access_type: '1'
  - meta_data:
      model_name: user
      date_created: '2020-09-29T10:44:15.106567252+03:30'
      date_modified: '2020-09-29T10:44:15.106567311+03:30'
    username: box
    password: password
    type: EMQUser
    ips:
    secret: secret
    token_expiration_duration: 2592000000000000
    rules:
    - uuid: e591af90-8191-4118-941a-7ef4434414ee
      endpoint: ''
      topic: box_event
      access_type: '1'
  - meta_data:
      model_name: user
      date_created: '2020-09-29T10:44:15.106569957+03:30'
      date_modified: '2020-09-29T10:44:15.106570022+03:30'
    username: colony-subscriber
    password: password
    type: EMQUser
    ips:
    secret: secret
    token_expiration_duration: 2592000000000000
    rules:
    - uuid: bcbe0a57-1706-4de7-a948-71c56c9700c4
      endpoint: ''
      topic: driver_location
      access_type: '1'
  - meta_data:
      model_name: user
      date_created: '2020-09-29T10:44:15.106573104+03:30'
      date_modified: '2020-09-29T10:44:15.106573162+03:30'
    username: gabriel
    password: password
    type: HeraldUser
    ips:
    secret: secret
    token_expiration_duration: 2592000000000000
    rules:
    - uuid: 305dc844-5df0-42dc-849b-deccfe2dab96
      endpoint: "/notification"
      topic: ''
      access_type: '2'
    - uuid: 5795227f-10a8-4822-ba5e-a1fc057a0a95
      endpoint: "/event"
      topic: ''
      access_type: '2'
  - meta_data:
      model_name: user
      date_created: '2021-06-23T08:42:24.722521722Z'
      date_modified: '2021-07-06T18:40:10.074710788Z'
    username: gossiper
    password: password
    type: EMQUser
    ips:
    secret: secret
    token_expiration_duration: 30758400000000000
    rules:
    - uuid: ec6f659e-fe73-41cd-805e-c5285bd92a8d
      endpoint: ''
      topic: shared_location
      access_type: '2'
    - uuid: a8dc06c4-bb11-4cb9-8da7-84ae34d2d14a
      endpoint: ''
      topic: driver_location
      access_type: '1'
    - uuid: cda59530-d412-4c6d-bb3b-7a89c6bf58c5
      endpoint: ''
      topic: passenger_location
      access_type: '1'
