---
namespace: ode
region: teh-1

labels:
  managedby: dispatching-team
  createdby: mozart

image:
  registry: image-registry.apps.private.okd4.teh-1.snappcloud.io
  repository: mozart/soteria
  tag: main
  pullPolicy: Always

config:
  validator:
    url: "http://validator:80"
    timeout: 10s

vendors:
  snapp:
    company: "snapp"
    hashid_map:
      0:
        salt: "secret"
        length: 15
      1:
        salt: "secret"
        length: 15
    allowed_access_types: [ "pub", "sub" ]
    topics:
      - type: cab_event
        template: ^{{IssToEntity .iss}}-event-{{ EncodeMD5 (DecodeHashID .sub .iss) }}$
        accesses:
          0: '1'
          1: '1'
      - type: driver_location
        template: ^{{.company}}/driver/{{.sub}}/location$
        accesses:
          0: '2'
          1: '-1'
      - type: passenger_location
        template: ^{{.company}}/passenger/{{.sub}}/location$
        hash_type: 0
        accesses:
          0: '2'
          1: '2'
      - type: superapp_event
        template: ^{{.company}}/{{IssToEntity .iss}}/{{.sub}}/superapp$
        accesses:
          0: '1'
          1: '1'
      - type: box_event
        template: ^bucks$
        hash_type: 0
        accesses:
          0: '-1'
          1: '-1'
      - type: shared_location
        template: ^{{.company}}/{{IssToEntity .iss}}/{{.sub}}/{{IssToPeer .iss}}-location$
        accesses:
          0: '1'
          1: '1'
      - type: chat
        template: ^{{.company}}/{{IssToEntity .iss}}/{{.sub}}/chat$
        accesses:
          0: '1'
          1: '1'
      - type: general_call_entry
        template: ^shared/{{.company}}/{{IssToEntity .iss}}/{{.sub}}/call/send$
        accesses:
          0: '2'
          1: '2'
      - type: node_call_entry
        template: ^{{.company}}/{{IssToEntity .iss}}/{{.sub}}/call/[a-zA-Z0-9-_]+/send$
        accesses:
          0: '2'
          1: '2'
      - type: call_outgoing
        template: ^{{.company}}/{{IssToEntity .iss}}/{{.sub}}/call/receive$
        accesses:
          0: '1'
          1: '1'
    keys:
      1: |-
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5SeRfOdTyvQZ7N9ahFHl
        +J05r7e9fgOQ2cpOtnnsIjAjCt1dF7/NkqVifEaxABRBGG9iXIw//G4hi0TqoKqK
        aoSHMGf6q9pSRLGyB8FatxZf2RBTgrXYqVvpasbnB1ZNv858yTpRjV9NzJXYHLp8
        8Hbd/yYTR6Q7ajs11/SMLGO7KBELsI1pBz7UW/fngJ2pRmd+RkG+EcGrOIZ27TkI
        Xjtog6bgfmtV9FWxSVdKACOY0OmW+g7jIMik2eZTYG3kgCmW2odu3zRoUa7l9VwN
        YMuhTePaIWwOifzRQt8HDsAOpzqJuLCoYX7HmBfpGAnwu4BuTZgXVwpvPNb+KlgS
        pQIDAQAB
        -----END PUBLIC KEY-----
      0: |-
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyG4XpV9TpDfgWJF9TiIv
        va4hNhDuqYMJO6iXLzr3y8oCvoB7zUK0EjtbLH+A3gr1kUvyZKDWT4qHTvU2Sshm
        X+ttWGK34EhCvF3Lb18yxmVDSSK8JIcTaJjMqmyubxzamQnNoWazJ7ea9BIo2YGL
        C9rgPbi1hihhdb07xPGUkJRqbWkI98xjDhKdMqiwW1hIRXm/apo++FjptvqvF84s
        ynC5gWGFHiGNICRsLJBczLEAf2Atbafigq6/tovzMabnp2yRtr1ReEgioH1RO4gX
        J7F4N5f6y/VWd8+sDOSxtS/HcnP/7g8/A54G2IbXxr+EiwOO/1F+pyMPKq7sGDSU
        DwIDAQAB
        -----END PUBLIC KEY-----
    iss_entity_map:
      0: "driver"
      1: "passenger"
      default: "none"
    iss_peer_map:
      0: "passenger"
      1: "driver"
      default: "none"
    jwt:
      iss_name: "iss"
      sub_name: "sub"
      signing_method: "RS512"

  snapp_pay:
    company: "snapp_pay"
    hashid_map:
      snpay:
        length: "20"
        salt: "UKjqkklfurigkvoslxp7vi0vcm66w"
        alphabet: "abcdefghijklmnopqrstuvwxyz1234567890"
    allowed_access_types: ["pub", "sub"]
    keys:
      snpay: "ZVFzRTBYT1pXYzk5Z2MzNkdjN2JJNzUwc2k4VUlp"
    iss_entity_map:
      snpay: "passenger"
      default: "none"
    iss_peer_map:
      default: "none"
    jwt:
      iss_name: "iss"
      sub_name: "ud"
      signing_method: "HS512"
    topics:
      - type: test
        template: snapp_pay/passenger/{{.sub}}/pay
        accesses:
          snpay: '1'
      - type: cab_event
        template: ^{{IssToEntity .iss}}-event-{{ EncodeMD5 (DecodeHashID .sub .iss) }}$
        accesses:
          snpay: '1'
