replicaCount: 1

labels:
  managedby: dispatching-team
  createdby: mozart

image:
  registry: image-registry.apps.private.okd4.teh-1.snappcloud.io
  repository: mozart/soteria
  tag: main
  pullPolicy: Always

timezone: Asia/Tehran

service:
  type: ClusterIP
  ports:
    - name: http
      port: 9999
      protocol: tcp

resources:
  limits:
    memory: 128Mi
    cpu: 200m
  requests:
    memory: 128Mi
    cpu: 100m

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 65

rollingParams:
  maxSurge: 5
  maxUnavailable: 0

serviceMonitor:
  enabled: false

config:
  http_port: 9999
  default_vendor: baly
  logger:
    level: "debug"
  tracer:
    enabled: true
    ratio: 1
    agent:
      host: 'jaeger-all-in-one-inmemory-agent'
      port: 6831

vendors:
  snapp:
    company: "baly"
    hashid_map:
      0:
        salt: "secret"
        length: 15
      1:
        salt: "secret"
        length: 15
    allowed_access_types: [ "pub", "sub" ]
    topics:
      - type: cab_event
        template: ^{{IssToEntity .iss}}-event-{{ EncodeMD5 (DecodeHashID .sub .iss) }}$
        hash_type: 1
        accesses:
          0: '1'
          1: '1'
      - type: driver_location
        template: ^{{.company}}/driver/{{.sub}}/location$
        hash_type: 0
        accesses:
          0: '2'
          1: '-1'
      - type: passenger_location
        template: ^{{.company}}/passenger/{{.sub}}/location$
        hash_type: 0
        accesses:
          0: '2'
          1: '2'
      - type: superapp_event
        template: ^{{.company}}/{{IssToEntity .iss}}/{{.sub}}/superapp$
        hash_type: 0
        accesses:
          0: '1'
          1: '1'
      - type: box_event
        template: ^bucks$
        hash_type: 0
        accesses:
          0: '-1'
          1: '-1'
      - type: shared_location
        template: ^{{.company}}/{{IssToEntity .iss}}/{{.sub}}/{{IssToPeer .iss}}-location$
        hash_type: 0
        accesses:
          0: '1'
          1: '1'
      - type: chat
        template: ^{{.company}}/{{IssToEntity .iss}}/{{.sub}}/chat$
        hash_type: 0
        accesses:
          0: '1'
          1: '1'
      - type: general_call_entry
        template: ^shared/{{.company}}/{{IssToEntity .iss}}/{{.sub}}/call/send$
        hash_type: 0
        accesses:
          0: '2'
          1: '2'
      - type: node_call_entry
        template: ^{{.company}}/{{IssToEntity .iss}}/{{.sub}}/call/[a-zA-Z0-9-_]+/send$
        hash_type: 0
        accesses:
          0: '2'
          1: '2'
      - type: call_outgoing
        template: ^{{.company}}/{{IssToEntity .iss}}/{{.sub}}/call/receive$
        hash_type: 0
        accesses:
          0: '1'
          1: '1'
    keys:
        0: |-
          LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF5RzRYcFY5VHBEZmdXSkY5VGlJdgp2YTRoTmhEdXFZTUpPNmlYTHpyM3k4b0N2b0I3elVLMEVqdGJMSCtBM2dyMWtVdnlaS0RXVDRxSFR2VTJTc2htClgrdHRXR0szNEVoQ3ZGM0xiMTh5eG1WRFNTSzhKSWNUYUpqTXFteXVieHphbVFuTm9XYXpKN2VhOUJJbzJZR0wKQzlyZ1BiaTFoaWhoZGIwN3hQR1VrSlJxYldrSTk4eGpEaEtkTXFpd1cxaElSWG0vYXBvKytGanB0dnF2Rjg0cwp5bkM1Z1dHRkhpR05JQ1JzTEpCY3pMRUFmMkF0YmFmaWdxNi90b3Z6TWFibnAyeVJ0cjFSZUVnaW9IMVJPNGdYCko3RjRONWY2eS9WV2Q4K3NET1N4dFMvSGNuUC83ZzgvQTU0RzJJYlh4citFaXdPTy8xRitweU1QS3E3c0dEU1UKRHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t
        1: |-
          LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE1U2VSZk9kVHl2UVo3TjlhaEZIbAorSjA1cjdlOWZnT1EyY3BPdG5uc0lqQWpDdDFkRjcvTmtxVmlmRWF4QUJSQkdHOWlYSXcvL0c0aGkwVHFvS3FLCmFvU0hNR2Y2cTlwU1JMR3lCOEZhdHhaZjJSQlRnclhZcVZ2cGFzYm5CMVpOdjg1OHlUcFJqVjlOekpYWUhMcDgKOEhiZC95WVRSNlE3YWpzMTEvU01MR083S0JFTHNJMXBCejdVVy9mbmdKMnBSbWQrUmtHK0VjR3JPSVoyN1RrSQpYanRvZzZiZ2ZtdFY5Rld4U1ZkS0FDT1kwT21XK2c3aklNaWsyZVpUWUcza2dDbVcyb2R1M3pSb1VhN2w5VndOCllNdWhUZVBhSVd3T2lmelJRdDhIRHNBT3B6cUp1TENvWVg3SG1CZnBHQW53dTRCdVRaZ1hWd3B2UE5iK0tsZ1MKcFFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t
    iss_entity_map:
      0: "driver"
      1: "passenger"
      default: "none"
    iss_peer_map:
      0: "passenger"
      1: "driver"
      default: "none"
    jwt:
      iss_name: "iss"
      sub_name: "sub"
      signing_method: "RS512"



