// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package contracts

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthContract struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	IPAddress            string   `protobuf:"bytes,2,opt,name=IPAddress,proto3" json:"IPAddress,omitempty"`
	Endpoint             string   `protobuf:"bytes,3,opt,name=Endpoint,proto3" json:"Endpoint,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=Password,proto3" json:"Password,omitempty"`
	Token                string   `protobuf:"bytes,6,opt,name=Token,proto3" json:"Token,omitempty"`
	Topic                string   `protobuf:"bytes,7,opt,name=Topic,proto3" json:"Topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthContract) Reset()         { *m = AuthContract{} }
func (m *AuthContract) String() string { return proto.CompactTextString(m) }
func (*AuthContract) ProtoMessage()    {}
func (*AuthContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *AuthContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthContract.Unmarshal(m, b)
}
func (m *AuthContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthContract.Marshal(b, m, deterministic)
}
func (m *AuthContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthContract.Merge(m, src)
}
func (m *AuthContract) XXX_Size() int {
	return xxx_messageInfo_AuthContract.Size(m)
}
func (m *AuthContract) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthContract.DiscardUnknown(m)
}

var xxx_messageInfo_AuthContract proto.InternalMessageInfo

func (m *AuthContract) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *AuthContract) GetIPAddress() string {
	if m != nil {
		return m.IPAddress
	}
	return ""
}

func (m *AuthContract) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *AuthContract) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthContract) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthContract) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthContract) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type ServiceResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceResponse) Reset()         { *m = ServiceResponse{} }
func (m *ServiceResponse) String() string { return proto.CompactTextString(m) }
func (*ServiceResponse) ProtoMessage()    {}
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *ServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceResponse.Unmarshal(m, b)
}
func (m *ServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceResponse.Marshal(b, m, deterministic)
}
func (m *ServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceResponse.Merge(m, src)
}
func (m *ServiceResponse) XXX_Size() int {
	return xxx_messageInfo_ServiceResponse.Size(m)
}
func (m *ServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceResponse proto.InternalMessageInfo

func (m *ServiceResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type GetTokenContract struct {
	GrantType            string   `protobuf:"bytes,1,opt,name=GrantType,proto3" json:"GrantType,omitempty"`
	ClientID             string   `protobuf:"bytes,2,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	ClientSecret         string   `protobuf:"bytes,3,opt,name=ClientSecret,proto3" json:"ClientSecret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenContract) Reset()         { *m = GetTokenContract{} }
func (m *GetTokenContract) String() string { return proto.CompactTextString(m) }
func (*GetTokenContract) ProtoMessage()    {}
func (*GetTokenContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *GetTokenContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenContract.Unmarshal(m, b)
}
func (m *GetTokenContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenContract.Marshal(b, m, deterministic)
}
func (m *GetTokenContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenContract.Merge(m, src)
}
func (m *GetTokenContract) XXX_Size() int {
	return xxx_messageInfo_GetTokenContract.Size(m)
}
func (m *GetTokenContract) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenContract.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenContract proto.InternalMessageInfo

func (m *GetTokenContract) GetGrantType() string {
	if m != nil {
		return m.GrantType
	}
	return ""
}

func (m *GetTokenContract) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *GetTokenContract) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

type GetTokenResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenResponse) Reset()         { *m = GetTokenResponse{} }
func (m *GetTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokenResponse) ProtoMessage()    {}
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *GetTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenResponse.Unmarshal(m, b)
}
func (m *GetTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenResponse.Merge(m, src)
}
func (m *GetTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokenResponse.Size(m)
}
func (m *GetTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenResponse proto.InternalMessageInfo

func (m *GetTokenResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthContract)(nil), "contracts.AuthContract")
	proto.RegisterType((*ServiceResponse)(nil), "contracts.ServiceResponse")
	proto.RegisterType((*GetTokenContract)(nil), "contracts.GetTokenContract")
	proto.RegisterType((*GetTokenResponse)(nil), "contracts.GetTokenResponse")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xd1, 0x4a, 0xfb, 0x30,
	0x14, 0xc6, 0xff, 0xdd, 0x7f, 0x9b, 0xeb, 0x71, 0xa0, 0x04, 0xc1, 0x50, 0x77, 0x31, 0x02, 0x82,
	0x57, 0xbb, 0xd0, 0x5b, 0xbd, 0x18, 0x55, 0xc7, 0x6e, 0x64, 0x74, 0xf3, 0x01, 0x6a, 0x7a, 0x60,
	0x45, 0x4d, 0x42, 0x92, 0x29, 0x3e, 0x84, 0xaf, 0xe6, 0x33, 0x49, 0x93, 0xa6, 0xad, 0x43, 0xbc,
	0x6a, 0xbe, 0xef, 0x57, 0x4e, 0xbf, 0x2f, 0xa7, 0x00, 0xf9, 0xce, 0x6e, 0x67, 0x4a, 0x4b, 0x2b,
	0x49, 0xcc, 0xa5, 0xb0, 0x3a, 0xe7, 0xd6, 0xb0, 0xaf, 0x08, 0xc6, 0xf3, 0x9d, 0xdd, 0xa6, 0xb5,
	0x43, 0xa6, 0x70, 0xb8, 0x46, 0xfd, 0x56, 0x72, 0x7c, 0xc8, 0x5f, 0x91, 0x46, 0xd3, 0xe8, 0x22,
	0xce, 0xba, 0x16, 0x99, 0x40, 0xbc, 0x5c, 0xcd, 0x8b, 0x42, 0xa3, 0x31, 0xb4, 0xe7, 0x78, 0x6b,
	0x90, 0x04, 0x46, 0x77, 0xa2, 0x50, 0xb2, 0x14, 0x96, 0xfe, 0x77, 0xb0, 0xd1, 0x15, 0x7b, 0x34,
	0xa8, 0x45, 0x35, 0xb8, 0xef, 0x59, 0xd0, 0x15, 0x5b, 0xe5, 0xc6, 0xbc, 0x4b, 0x5d, 0xd0, 0x81,
	0x67, 0x41, 0x93, 0x13, 0x18, 0x6c, 0xe4, 0x33, 0x0a, 0x3a, 0x74, 0xc0, 0x0b, 0xef, 0xaa, 0x92,
	0xd3, 0x83, 0xe0, 0xaa, 0x92, 0xb3, 0x73, 0x38, 0xaa, 0xc3, 0x66, 0x68, 0x94, 0x14, 0x06, 0x09,
	0x81, 0x7e, 0x2a, 0x0b, 0xdf, 0x65, 0x90, 0xb9, 0x33, 0x53, 0x70, 0xbc, 0x40, 0xeb, 0x06, 0x35,
	0xd5, 0x27, 0x10, 0x2f, 0x74, 0x2e, 0xec, 0xe6, 0x43, 0x85, 0xe2, 0xad, 0x51, 0x05, 0x4c, 0x5f,
	0x4a, 0x14, 0x76, 0x79, 0x5b, 0xb7, 0x6e, 0x34, 0x61, 0x30, 0xf6, 0xe7, 0x35, 0x72, 0x8d, 0xa1,
	0xf8, 0x0f, 0x8f, 0x5d, 0xb7, 0x5f, 0xfc, 0x2b, 0x59, 0x5b, 0xb6, 0xd7, 0x29, 0x7b, 0xf9, 0x19,
	0x41, 0xbf, 0xda, 0x13, 0xb9, 0xa9, 0x9f, 0xa7, 0xb3, 0x66, 0x89, 0xb3, 0xee, 0x02, 0x93, 0xa4,
	0x03, 0xf6, 0x6e, 0x82, 0xfd, 0x23, 0xf7, 0x30, 0x0a, 0x29, 0xc8, 0x59, 0xe7, 0xcd, 0xfd, 0xcb,
	0x48, 0x7e, 0x83, 0xed, 0x9c, 0xa7, 0xa1, 0xfb, 0x93, 0xae, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x00, 0x55, 0xf1, 0x67, 0x57, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	Auth(ctx context.Context, in *AuthContract, opts ...grpc.CallOption) (*ServiceResponse, error)
	GetToken(ctx context.Context, in *GetTokenContract, opts ...grpc.CallOption) (*GetTokenResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Auth(ctx context.Context, in *AuthContract, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/contracts.Auth/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetToken(ctx context.Context, in *GetTokenContract, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	out := new(GetTokenResponse)
	err := c.cc.Invoke(ctx, "/contracts.Auth/GetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	Auth(context.Context, *AuthContract) (*ServiceResponse, error)
	GetToken(context.Context, *GetTokenContract) (*GetTokenResponse, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) Auth(ctx context.Context, req *AuthContract) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (*UnimplementedAuthServer) GetToken(ctx context.Context, req *GetTokenContract) (*GetTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToken not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contracts.Auth/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Auth(ctx, req.(*AuthContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contracts.Auth/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetToken(ctx, req.(*GetTokenContract))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "contracts.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _Auth_Auth_Handler,
		},
		{
			MethodName: "GetToken",
			Handler:    _Auth_GetToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
