---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "soteria.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "soteria.labels" . | nindent 4 }}
data:
  config.yaml: |
    allowed_access_types: {{ .Values.envs.allowed_access_types }}
    passenger_hash_length: {{ .Values.authEnvs.passenger_hash_length }}
    driver_hash_length: {{ .Values.authEnvs.driver_hash_length }}
    passenger_salt: {{ .Values.authEnvs.passenger_salt }}
    driver_salt: {{ .Values.authEnvs.driver_salt }}
    jwt:
      path: {{ .Values.authEnvs.jwt_keys_path }}
    logger:
      level: {{ .Values.envs.logger_level }}
    http_port: 9999
    {{ with .Values.envs.tracer }}
    tracer:
      enabled: {{ .enabled }}
      service_name: {{ .service_name }}
      sampler_type: {{ .sampler_type }}
      sampler_param: {{ .sampler_param }}
      host: {{ .host }}
      port: {{ .port }}
    {{ end }}
    {{ with .Values.envs.company }}
    company: {{ . }}
    {{ end }}
    {{ with .Values.users }}
    users:
      {{ toYaml . | nindent 8 }}
    {{ end }}
