---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "soteria.fullname" . }}-jwt-keys
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "soteria.labels" . | nindent 4 }}

stringData:
  {{- range $key, $value := .Values.jwtKeys }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
