apiVersion: v1
kind: Secret
metadata:
  name: {{ include "soteria.fullname" . }}-auth-envs
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "soteria.labels" . | nindent 4 }}
stringData:
    {{- range $key, $value := .Values.authEnvs }}
    {{- if $value }}
    SOTERIA_{{ $key | upper }}: {{ $value | quote }}
    {{- end }}
    {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "soteria.fullname" . }}-jwt-keys
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "soteria.labels" . | nindent 4 }}
    
stringData:
  {{- range $key, $value := .Values.jwtKeys }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
