apiVersion: v1
kind: Template
metadata:
  name: ${SERVICE_NAME}-configmap
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${SERVICE_NAME}-env
      labels:
        app.snappcloud.io/name: ${SERVICE_NAME}
        app.snappcloud.io/instance: ${SERVICE_NAME}-${CI_COMMIT_REF_SLUG}
        app.snappcloud.io/version: ${CI_COMMIT_REF_SLUG}
        app.snappcloud.io/managed-by: ${MANAGED_BY}
        app.snappcloud.io/created-by: mozart
        app: ${SERVICE_NAME}
    data:
       SOTERIA_HTTP_PORT: "9999"
       SOTERIA_GRPC_PORT: "50051"
       SOTERIA_REDIS_ADDRESS: "${REDIS_ADDR}"
       SOTERIA_REDIS_POOL_SIZE: "10"
       SOTERIA_REDIS_MAX_RETRIES: "0"
       SOTERIA_REDIS_READ_TIMEOUT: "3s"
       SOTERIA_REDIS_POOL_TIMEOUT: "4s"
       SOTERIA_REDIS_MIN_RETRY_BACKOFF: "8ms"
       SOTERIA_REDIS_MAX_RETRY_BACKOFF: "512ms"
       SOTERIA_REDIS_IDLE_TIMEOUT: "300s"
       SOTERIA_REDIS_IDLE_CHECK_FREQUENCY: "60s"
       SOTERIA_REDIS_SET_MEMBER_EXP_TIME: "300s"
       SOTERIA_LOGGER_LEVEL: "${LOG_LEVEL}"
       SOTERIA_LOGGER_SENTRY_ENABLED: "false"
       SOTERIA_LOGGER_SENTRY_DSN: ""
       SOTERIA_LOGGER_SENTRY_TIMEOUT: "500ms"
       SOTERIA_ALLOWED_ACCESS_TYPES: "sub,pub" 

parameters:
  - name: SERVICE_NAME
    displayName: Service name
    required: true
    value: "soteria"
  - name: MANAGED_BY
    displayName: Created By
    required: true
    value: dispatching-team
  - name: CI_COMMIT_REF_SLUG
    displayName: Commit Ref Slug
    required: true
    value: "dev"
  - name: LOG_LEVEL
    value: "DEBUG"
    displayName: Log Level
    description: How much log do you want? (DEBUG|INFO|WARN|ERROR|OFF)
  - name: REDIS_ADDR
    required: true
    value: "rediscentral:6379"
