apiVersion: v1
kind: Template
metadata:
  name: "${SERVICE_NAME}-secret"
objects:
  - apiVersion: v1
    kind: Secret
    type: Opaque
    metadata:
      name: "${SERVICE_NAME}-auth-env"
      labels:
        app: "${SERVICE_NAME}"
        app.snappcloud.io/created-by: "mozart"
        app.snappcloud.io/managed-by: "${MANAGED_BY}"
        app.snappcloud.io/version: "${APP_VERSION}"
        app.snappcloud.io/instance: "${SERVICE_NAME}-${CI_COMMIT_REF_SLUG}"
    stringData:
      SOTERIA_JWT_KEYS_PATH: "${JWT_KEYS_PATH}"
      SOTERIA_DRIVER_SALT: "${DRIVER_HASH_SALT}"
      SOTERIA_PASSENGER_SALT: "${PASSENGER_HASH_SALT}"
      SOTERIA_DRIVER_HASH_LENGTH: "${DRIVER_HASH_LENGTH}"
      SOTERIA_PASSENGER_HASH_LENGTH: "${PASSENGER_HASH_LENGTH}"
  - apiVersion: v1
    kind: Secret
    type: Opaque
    metadata:
      name: "${SERVICE_NAME}-jwt-keys"
      labels:
        app: "${SERVICE_NAME}"
        app.snappcloud.io/created-by: "mozart"
        app.snappcloud.io/managed-by: "${MANAGED_BY}"
        app.snappcloud.io/version: "${APP_VERSION}"
        app.snappcloud.io/instance: "${SERVICE_NAME}-${CI_COMMIT_REF_SLUG}"
    stringData:
      0.pem: "${DRIVER_JWT_PUBLIC_KEY}"
      1.pem: "${PASSENGER_JWT_PUBLIC_KEY}"
      100.pem: "${THIRD_PARTY_JWT_PUBLIC_KEY}"
      100.private.pem: "${THIRD_PARTY_JWT_PRIVATE_KEY}"
  - apiVersion: v1
    kind: Secret
    type: Opaque
    metadata:
      name: "${SERVICE_NAME}-db"
      labels:
        app: "${SERVICE_NAME}"
        app.snappcloud.io/created-by: "mozart"
        app.snappcloud.io/managed-by: "${MANAGED_BY}"
        app.snappcloud.io/version: "${APP_VERSION}"
        app.snappcloud.io/instance: "${SERVICE_NAME}-${CI_COMMIT_REF_SLUG}"
    stringData:
      db.json: "${DB}"


parameters:
  - name: SERVICE_NAME
    displayName: Service name
    description: The name of the application (should be unique in the namespace)
    value: "soteria"
  - name: APP_VERSION
    required: true
    value: "dev"
  - name: MANAGED_BY
    displayName: Managed by
    required: true
    value: "dispatching-team"
  - name: CI_COMMIT_REF_SLUG
    displayName: Commit Ref Slug
    required: true
    value: "dev"
  - name: PASSENGER_HASH_SALT
    displayName: Passenger hash salt for HashIds
    required: true
    value: "secret"
  - name: PASSENGER_HASH_LENGTH
    displayName: Minimum length of passenger generated hash for HashIds
    value: "15"
  - name: DRIVER_HASH_SALT
    displayName: Passenger hash salt for HashIds
    required: true
    value: "secret"
  - name: DRIVER_HASH_LENGTH
    displayName: Minimum length of driver generated hash for HashIds
    value: "15"
  - name: JWT_KEYS_PATH
    displayName: Private Key Path
    description: Private key Path
    value: "/jwt_pems/"
    required: true
  - name: THIRD_PARTY_JWT_PRIVATE_KEY
    displayName: Third Party JWT Private Key
    required: true
    value: |-
      -----BEGIN RSA PRIVATE KEY-----
      MIICWwIBAAKBgQCTxwVGmWzJNOaZnBRL+9/V1Mc8OWWzUDxlG2kL+0WxHh8/+76n
      gIvp7YsHHxUadR0iY6NkzLgFv+sBkKh523Nx0YtuGgmGuuVTaD27G2inwgFDabUs
      AKISBbn6d6jwlkfk3D+O6h5pdLqoI64Zq/NPmD0oWsupn2HVhMSjFbE6dwIDAQAB
      AoGAJDRGHp3IASNsu4V5k4QJuqF+jkqhl+S4Zyzn939/+3ydu1c5xl+/53fC7+O1
      j93RXXN7vF5LV11FfgSqwe/5wDEcAtyLXWPCHtLB1CIYFfqHxgwOQm4gQSyOgBnP
      hMccyv0VCDK23+Mk37lLkuON6xXMC8+IUq5UW/aadxkeqoECQQDU9Z5IFCmp3Ibs
      hJXx/x+ZQI+gLj0hh71pQEO2zqhu19i+M62KKnDb7k2OtK9IJR2ucU+YE3SXGShh
      1sPmgfVfAkEAsaTtZ1oZmszOs5TPYhs2e7LKLPNADZ36GVsG2h1FHVX+LyNkwk/E
      pn+FV3Dd1vkzxG/a3znEKz+2BJiz4vF56QJATUxKA4euB8XQA5Gsi4Y7Bfl1KIMg
      FUeb7NQyv+wLHxChz4gaeYgmJu48oIvdA6bVOzhN17lYHHA5RCocOVL6qQJAdHdT
      6nmo5dO3BQfgO0rqGolqgbPtX8AeE3eZc3DTOluBrbf/vGF95UcfzedCmkmBxh0r
      m0SNN2mq1TKkZXq52QJAIjxhG7spkOSZJQnVBA9TfLYZFM/aUzDpLxflvFAuJuqJ
      l+PFsbek2Zl6fgy294dXRvQhp1PJryngDaXTBiWK6g==
      -----END RSA PRIVATE KEY-----
  - name: DRIVER_JWT_PUBLIC_KEY
    displayName: Driver public key
    description: Public Key of driver's token
    required: true
    value: |-
      -----BEGIN PUBLIC KEY-----
      MIIBITANBgkqhkiG9w0BAQEFAAOCAQ4AMIIBCQKCAQBk7O6M5p4eYNAwtVU2beGa
      W4mhFG94OtYUWDl1E7UUrhUNGf97Eb/45NjQszu0YPERnApJc2RUm2TrS7iq0mHz
      Xbwf+CbNF54Q5mjuHcpBKgvFwUUSCCYBftmRc4xbFIH4Oh3nHC2GeukUS9TmJwjM
      tJKyU0Ve8BK5BgjhagM7XSs+scE2mxemoWtcs6mJLtBuEgRGMgHW00mSdOcLp/+l
      oHpSzRYN92/DomwmmjGVy8Ji0faeHx+r79ZzE0E8Rcc29Yhrg1ymrjfkXg98WjAb
      TSv4UAN20lsBDejpnGEZKJrxHZ56gHgaJn6PKKCD6ItJA7y7iraCdBhCfAIUIz/z
      AgMBAAE=
      -----END PUBLIC KEY-----
  - name: PASSENGER_JWT_PUBLIC_KEY
    displayName: Passenger public key
    description: Public Key of passenger's token
    required: true
    value: |-
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1lNRwyNsDieWs6LvHOJ+
      GyehhRC4Pn5yL5edKP3565F3LtRDMrkzwDRsQbqnUtTea9HCdTdBv+lI8vE17qRi
      RQn10IMaIH6e4Aa3OWNClFhuqNOag7VmffsjTOgxHgHpfGAKVF/4BwqOHrdHFbAD
      VOiWB1hv9Uc0C5laffGAub7fj+EAI02zlrsNDxYW8vyF2H47N7VWcvgd3RhZpxlG
      8bq9phl7Ja55YmQiT2Ic3/K5tsazg5z9lz6OTrx+JvWbefHFlJpjCLz5yefEaRmX
      9L/zyDMi4jgFTZEWNXC2vIrxwZMFwFhBXEp0PcCbuHJgJIucbRrbwukQC16uHJwP
      zQIDAQAB
      -----END PUBLIC KEY-----
  - name: THIRD_PARTY_JWT_PUBLIC_KEY
    displayName: Third party public key
    description: Public key of third parties
    required: true
    value: |-
      -----BEGIN PUBLIC KEY-----
      MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCTxwVGmWzJNOaZnBRL+9/V1Mc8
      OWWzUDxlG2kL+0WxHh8/+76ngIvp7YsHHxUadR0iY6NkzLgFv+sBkKh523Nx0Ytu
      GgmGuuVTaD27G2inwgFDabUsAKISBbn6d6jwlkfk3D+O6h5pdLqoI64Zq/NPmD0o
      Wsupn2HVhMSjFbE6dwIDAQAB
      -----END PUBLIC KEY-----
  - name: DB
    displayName: Initial database state
    description: Initial database state
    required: true
    value: |-
      [{"meta_data":{"model_name":"user","date_created":"2020-09-29T10:44:15.106544359+03:30","date_modified":"2020-09-29T10:44:15.106544423+03:30"},"username":"driver","password":"password","type":"EMQUser","ips":null,"secret":"secret","token_expiration_duration":2592000000000000,"rules":[{"uuid":"84df6017-a850-42a3-a06f-22306a006a8d","endpoint":"","topic":"cab_event","access_type":"1"},{"uuid":"df0b884e-41dc-444e-81d4-67f62ae2174c","endpoint":"","topic":"driver_location","access_type":"2"},{"uuid":"1375192a-6fc5-4409-abd8-0d21ef106bee","endpoint":"","topic":"shared_location","access_type":"1"},{"uuid":"d7aeb294-6271-470a-987a-01ea4f035e5d","endpoint":"","topic":"superapp_event","access_type":"1"},{"uuid":"d7aeb294-6271-470a-987a-04ea4fw35e4d","endpoint":"","topic":"call_entry","access_type":"2"},{"uuid":"d7aeb193-6271-470b-987a-04ca4fw35e4z","endpoint":"","topic":"call_outgoing","access_type":"1"}]},{"meta_data":{"model_name":"user","date_created":"2020-09-29T10:44:15.106560757+03:30","date_modified":"2020-09-29T10:44:15.106560814+03:30"},"username":"passenger","password":"password","type":"EMQUser","ips":null,"secret":"secret","token_expiration_duration":2592000000000000,"rules":[{"uuid":"a51f1898-3381-456f-a5fe-0e9d80b5bee0","endpoint":"","topic":"cab_event","access_type":"1"},{"uuid":"8de97e3f-e772-4da4-8f15-4dc048f5c06e","endpoint":"","topic":"superapp_event","access_type":"1"},{"uuid":"c41260ed-70eb-4554-bc15-5714fc1bf3f8","endpoint":"","topic":"passenger_location","access_type":"2"},{"uuid":"1375192a-6fc5-4409-abd8-0d21ef106bee","endpoint":"","topic":"shared_location","access_type":"1"},{"uuid":"d7eeb394-6271-470a-987a-04ea4fw35w4f","endpoint":"","topic":"call_entry","access_type":"2"},{"uuid":"d7aeb18r-6271-470b-982c-04cb4fz35e4c","endpoint":"","topic":"call_outgoing","access_type":"1"}]},{"meta_data":{"model_name":"user","date_created":"2020-09-29T10:44:15.106567252+03:30","date_modified":"2020-09-29T10:44:15.106567311+03:30"},"username":"box","password":"password","type":"EMQUser","ips":null,"secret":"secret","token_expiration_duration":2592000000000000,"rules":[{"uuid":"e591af90-8191-4118-941a-7ef4434414ee","endpoint":"","topic":"box_event","access_type":"1"}]},{"meta_data":{"model_name":"user","date_created":"2020-09-29T10:44:15.106569957+03:30","date_modified":"2020-09-29T10:44:15.106570022+03:30"},"username":"colony-subscriber","password":"password","type":"EMQUser","ips":null,"secret":"secret","token_expiration_duration":2592000000000000,"rules":[{"uuid":"bcbe0a57-1706-4de7-a948-71c56c9700c4","endpoint":"","topic":"driver_location","access_type":"1"}]},{"meta_data":{"model_name":"user","date_created":"2020-09-29T10:44:15.106573104+03:30","date_modified":"2020-09-29T10:44:15.106573162+03:30"},"username":"gabriel","password":"password","type":"HeraldUser","ips":null,"secret":"secret","token_expiration_duration":2592000000000000,"rules":[{"uuid":"305dc844-5df0-42dc-849b-deccfe2dab96","endpoint":"\/notification","topic":"","access_type":"2"},{"uuid":"5795227f-10a8-4822-ba5e-a1fc057a0a95","endpoint":"\/event","topic":"","access_type":"2"}]},{"meta_data":{"model_name":"user","date_created":"2021-06-23T08:42:24.722521722Z","date_modified":"2021-07-06T18:40:10.074710788Z"},"username":"gossiper","password":"password","type":"EMQUser","ips":null,"secret":"secret","token_expiration_duration":30758400000000000,"rules":[{"uuid":"ec6f659e-fe73-41cd-805e-c5285bd92a8d","endpoint":"","topic":"shared_location","access_type":"2"},{"uuid":"a8dc06c4-bb11-4cb9-8da7-84ae34d2d14a","endpoint":"","topic":"driver_location","access_type":"1"},{"uuid":"cda59530-d412-4c6d-bb3b-7a89c6bf58c5","endpoint":"","topic":"passenger_location","access_type":"1"}]}]
