---
swagger: '2.0'
info:
  version: 5.0.0
  title: Soteria

paths:
  /auth:
    post:
      summary: Authenticates EMQ user's connection request
      produces:
        - text
      consumes:
        - application/json
      parameters:
        - in: body
          name: request
          description: Request body
          schema:
            $ref: '#/definitions/auth'
      responses:
        401:
          description: Request is not authorized
        400:
          description: Bad input parameter
        200:
          description: >
            if body is empty means OK,
            if contains "ignore" it means request is ignored

  /acl:
    post:
      summary: Authorizes EMQ user's subscription request
      produces:
        - text
      consumes:
        - application/json
      parameters:
        - in: body
          name: request
          description: Request body
          schema:
            $ref: '#/definitions/acl'
      responses:
        401:
          description: Request is not authorized
        400:
          description: Bad input parameter
        200:
          description: OK

definitions:
  auth:
    type: object
    required:
      - token
    properties:
      token:
        type: string

  acl:
    type: object
    required:
      - token
      - topic
      - access
    properties:
      token:
        type: string
      topic:
        type: string
        example: "/snapp/driver/123/location"
      access:
        type: string
        enum: ["1", "2", "3"]
        example: "1"
